- name: "Query pacman DB for package that owns {{ file_path }}"
  command: pacman -Qo "{{ file_path }}"
  register: pkg_query
  failed_when: "'error:' in pkg_query.stderr"
  changed_when: false

- name: "Create upgrade-hook to handle pacnew for '{{ file_path }}'"
  template:
    dest: "{{ pacman_hooks_dir }}/{{ owning_package_name }}-{{ file_path | basename }}.hook"
    src: 'upgrade_hook.j2'
    owner: 'root'
    group: 'root'
    mode: '644'
    force: yes
  vars:
    owning_package_name: "{{ pkg_query.stdout | regex_replace('.* owned by (\\S+).*', '\\1') }}"
    dot_pacnew_file_path: "{{ file_path }}.pacnew"
  become: true
  become_user: root

